services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - observability

  apm:
    image: docker.elastic.co/apm/apm-server:8.10.2
    container_name: apm
    depends_on:
     - elasticsearch
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
    ports:
      - "8200:8200"
    networks:
      - observability

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.10.2
    container_name: metricbeat
    depends_on:
      - elasticsearch
    user: root 
    volumes:
      - "./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - observability

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.10.2
    container_name: heartbeat
    depends_on:
      - elasticsearch
    volumes:
      - "./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro"
    networks:
      - observability

networks:
  observability:
    external: true 