services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - observability

  apm:
    image: docker.elastic.co/apm/apm-server:7.17.10
    container_name: apm
    restart: on-failure
    depends_on:
     - elasticsearch
    volumes:      
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    networks:
      - observability

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.10
    container_name: metricbeat
    user: root 
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure
    networks:
      - observability

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.17.10
    container_name: heartbeat
    environment: 
      - setup.kibana.host=kibana:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    networks:
      - observability

networks:
  observability:
    external: true
